// Copyright 2022 The Engula Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: engula/v1/metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DatabaseDesc) Reset() {
	*x = DatabaseDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engula_v1_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatabaseDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseDesc) ProtoMessage() {}

func (x *DatabaseDesc) ProtoReflect() protoreflect.Message {
	mi := &file_engula_v1_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseDesc.ProtoReflect.Descriptor instead.
func (*DatabaseDesc) Descriptor() ([]byte, []int) {
	return file_engula_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseDesc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DatabaseDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CollectionDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Db   uint64 `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"` // database id
	// Types that are assignable to Partition:
	//	*CollectionDesc_Hash
	//	*CollectionDesc_Range
	Partition isCollectionDesc_Partition `protobuf_oneof:"partition"`
}

func (x *CollectionDesc) Reset() {
	*x = CollectionDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engula_v1_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionDesc) ProtoMessage() {}

func (x *CollectionDesc) ProtoReflect() protoreflect.Message {
	mi := &file_engula_v1_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionDesc.ProtoReflect.Descriptor instead.
func (*CollectionDesc) Descriptor() ([]byte, []int) {
	return file_engula_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionDesc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectionDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionDesc) GetDb() uint64 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (m *CollectionDesc) GetPartition() isCollectionDesc_Partition {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (x *CollectionDesc) GetHash() *CollectionDesc_HashPartition {
	if x, ok := x.GetPartition().(*CollectionDesc_Hash); ok {
		return x.Hash
	}
	return nil
}

func (x *CollectionDesc) GetRange() *CollectionDesc_RangePartition {
	if x, ok := x.GetPartition().(*CollectionDesc_Range); ok {
		return x.Range
	}
	return nil
}

type isCollectionDesc_Partition interface {
	isCollectionDesc_Partition()
}

type CollectionDesc_Hash struct {
	Hash *CollectionDesc_HashPartition `protobuf:"bytes,4,opt,name=hash,proto3,oneof"`
}

type CollectionDesc_Range struct {
	Range *CollectionDesc_RangePartition `protobuf:"bytes,5,opt,name=range,proto3,oneof"`
}

func (*CollectionDesc_Hash) isCollectionDesc_Partition() {}

func (*CollectionDesc_Range) isCollectionDesc_Partition() {}

type CollectionDesc_HashPartition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slots uint32 `protobuf:"varint,1,opt,name=slots,proto3" json:"slots,omitempty"`
}

func (x *CollectionDesc_HashPartition) Reset() {
	*x = CollectionDesc_HashPartition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engula_v1_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionDesc_HashPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionDesc_HashPartition) ProtoMessage() {}

func (x *CollectionDesc_HashPartition) ProtoReflect() protoreflect.Message {
	mi := &file_engula_v1_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionDesc_HashPartition.ProtoReflect.Descriptor instead.
func (*CollectionDesc_HashPartition) Descriptor() ([]byte, []int) {
	return file_engula_v1_metadata_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CollectionDesc_HashPartition) GetSlots() uint32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

type CollectionDesc_RangePartition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectionDesc_RangePartition) Reset() {
	*x = CollectionDesc_RangePartition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engula_v1_metadata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionDesc_RangePartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionDesc_RangePartition) ProtoMessage() {}

func (x *CollectionDesc_RangePartition) ProtoReflect() protoreflect.Message {
	mi := &file_engula_v1_metadata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionDesc_RangePartition.ProtoReflect.Descriptor instead.
func (*CollectionDesc_RangePartition) Descriptor() ([]byte, []int) {
	return file_engula_v1_metadata_proto_rawDescGZIP(), []int{1, 1}
}

var File_engula_v1_metadata_proto protoreflect.FileDescriptor

var file_engula_v1_metadata_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x6e, 0x67, 0x75,
	0x6c, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x32, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x02, 0x0a, 0x0e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x64, 0x62,
	0x12, 0x3d, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x65, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12,
	0x40, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x65, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x1a, 0x25, 0x0a, 0x0d, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x1a, 0x10, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engula_v1_metadata_proto_rawDescOnce sync.Once
	file_engula_v1_metadata_proto_rawDescData = file_engula_v1_metadata_proto_rawDesc
)

func file_engula_v1_metadata_proto_rawDescGZIP() []byte {
	file_engula_v1_metadata_proto_rawDescOnce.Do(func() {
		file_engula_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_engula_v1_metadata_proto_rawDescData)
	})
	return file_engula_v1_metadata_proto_rawDescData
}

var file_engula_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_engula_v1_metadata_proto_goTypes = []interface{}{
	(*DatabaseDesc)(nil),                  // 0: engula.v1.DatabaseDesc
	(*CollectionDesc)(nil),                // 1: engula.v1.CollectionDesc
	(*CollectionDesc_HashPartition)(nil),  // 2: engula.v1.CollectionDesc.HashPartition
	(*CollectionDesc_RangePartition)(nil), // 3: engula.v1.CollectionDesc.RangePartition
}
var file_engula_v1_metadata_proto_depIdxs = []int32{
	2, // 0: engula.v1.CollectionDesc.hash:type_name -> engula.v1.CollectionDesc.HashPartition
	3, // 1: engula.v1.CollectionDesc.range:type_name -> engula.v1.CollectionDesc.RangePartition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engula_v1_metadata_proto_init() }
func file_engula_v1_metadata_proto_init() {
	if File_engula_v1_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engula_v1_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatabaseDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engula_v1_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engula_v1_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionDesc_HashPartition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engula_v1_metadata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionDesc_RangePartition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_engula_v1_metadata_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CollectionDesc_Hash)(nil),
		(*CollectionDesc_Range)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engula_v1_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engula_v1_metadata_proto_goTypes,
		DependencyIndexes: file_engula_v1_metadata_proto_depIdxs,
		MessageInfos:      file_engula_v1_metadata_proto_msgTypes,
	}.Build()
	File_engula_v1_metadata_proto = out.File
	file_engula_v1_metadata_proto_rawDesc = nil
	file_engula_v1_metadata_proto_goTypes = nil
	file_engula_v1_metadata_proto_depIdxs = nil
}
